<template>
  <div>
    <div id="active" v-if="cards.length > 0">
      <h2>Active Flashcards</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th class="hide-mobile">Card Id</th>
            <th class="hide-mobile">Bin</th>
            <th>Times incorrect</th>
            <th>Question</th>
            <th class="hide-mobile">Answer</th>
            <th>Becomes active</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="card in cards" :key="card.cardId">
            <td>
              <font-awesome-icon
                v-on:click="
                  editCard(card)"
                icon="fa-solid fa-edit icon action"
                title="Edit card"
              ></font-awesome-icon>
            </td>
                        <td>
              <font-awesome-icon
                v-on:click="
                  deleteCard(card)"
                icon="fa-solid fa-trash-can icon action"
                title="Delete card"
              ></font-awesome-icon>
            </td>
            <td class="hide-mobile" id="card-id">{{ card.cardId }}</td>
            <td class="hide-mobile" id="bin">{{ card.bin }}</td>
            <td id="incorrect">{{ card.timesWrong }}</td>
            <td id="question">{{ card.question }}</td>
            <td class="hide-mobile" id="answer">{{ card.answer }}</td>
            <td id="time-stamp">{{ formatTimestamp(card.expiryTime) }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div id="inactive" v-if="inactiveCards.length > 0">
      <h2>Inactive Flashcards</h2>
      <table>
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th class="hide-mobile">Card Id</th>
            <th class="hide-mobile" >Bin</th>
            <th>Times incorrect</th>
            <th>Question</th>
            <th class="hide-mobile">Answer</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="card in inactiveCards" :key="card.cardId">
                        <td>
              <font-awesome-icon
                v-on:click="
                  editCard(card)" 
                icon="fa-solid fa-edit icon action"
                title="Delete card"
              ></font-awesome-icon>
            </td>
                        <td>
              <font-awesome-icon
                v-on:click="
                  deleteCard(card)"
                icon="fa-solid fa-trash-can icon action"
                title="Edit card"
              ></font-awesome-icon>
            </td>
            <td class="hide-mobile" id="card-id">{{ card.cardId }}</td>
            <td class="hide-mobile" id="bin">{{ card.bin }}</td>
            <td id="incorrect">{{ card.timesWrong }}</td>
            <td id="question">{{ card.question }}</td>
            <td class="hide-mobile" id="answer">{{ card.answer }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div v-if="cards.length == 0 && inactiveCards.length == 0">
      <h2>There are currently no cards in your collection.</h2>
    </div>
  </div>
</template>

<script>
import cardServ from "../services/CardService";
import timeServ from "../services/TimeService";

export default {
  name: "flashcard-collection",
  data() {
    return {
      cards: [],
      inactiveCards: [],
      login: false
    };
  },
  created() {
   
    this.populatePage();

  },
  methods: {
    editCard(card) {
      this.$router.push( {name: 'Edit', params: {card: card}})
    },
    deleteCard(card) {
      this.$router.push( {name: 'Delete', params: {card: card}})
    },
    populatePage() {
      
      if(this.login) {
        cardServ.getAllActiveCardsByUser().then((response) => {  
          this.cards = response.data;
          
        });
        cardServ.getAllInactiveCardsByUser().then((response) => {
        this.inactiveCards = response.data;
        
        });
      } else {
      this.cards = this.$store.state.cards
        .filter(element => element.bin < 11 && element.timesWrong < 10)
        .sort((a,b) => {
          if (
            (
              new Date(a.expiryTime) - new Date(timeServ.nowUTC().toISOString()) > 0 || 
              new Date(b.expiryTime) - new Date(timeServ.nowUTC().toISOString()) > 0
            ) &&
            ( a != b )
          ) {
            return new Date (a.expiryTime) - new Date(b.expiryTime);
          } else {
            return b.bin - a.bin;
          }
        });
      
      this.inactiveCards = this.$store.state.cards
        .filter(element => element.bin >= 11 || element.timesWrong >= 10);
      
      }
      
    },

    formatTimestamp(timeStamp) {
      if (timeStamp == null) {
        return "N/A";
      } else {
        return this.remainingTime(this.getTimeDifference(timeStamp));
      }
    },

    //the following method was generated by ChatGPT 3.5
    getTimeDifference(date) {
      const utcDate = timeServ.nowUTC().toISOString(); // Get the current date/time

      const difference = new Date(date) - new Date(utcDate); // Calculate the difference in millisecond

      // Convert the difference to the desired units (e.g., seconds, minutes, hours, etc.)
      const seconds = Math.floor(difference / 1000);
      const minutes = Math.floor(seconds / 60);
      const hours = Math.floor(minutes / 60);
      const days = Math.floor(hours / 24);

      // Return an object with the difference in various units
      return {
        milliseconds: difference,
        seconds: seconds,
        minutes: minutes,
        hours: hours,
        days: days,
      };
    },

    remainingTime(time) {
      if (time.days > 0) {
        return time.days + " days";
      } else if (time.hours > 0) {
        return time.hours + " hours";
      } else if (time.minutes > 0) {
        return time.minutes + " minutes";
      } else if (time.seconds > 0) {
        return time.seconds + " seconds";
      } else {
        return "Now";
      }
    },
  },
};
</script>

<style>
th {
  font-weight: bold;
  padding-right: 1em;
  text-align: center;
}

td {
  padding-right: 1em;
}

thead {
  border-bottom: 1px solid black;
}

tbody td {
  padding-top: 0.5em;
}

#card-id,
#bin,
#time-stamp,
#incorrect {
  text-align: center;
}

#inactive {
  margin-top: 2em;
}

@media (max-width: 576px) {
  .hide-mobile {
    display: none;
  }
}
</style>